import edu.rit.ds.RemoteEvent;

/**
 * Class JobSchedulerEvent is a remote event generated by the JobScheduler
 * These events are related to scheduling jobs, performing jobs, and finishing
 * jobs.  These events report to the Logger object.
 *
 * @author Matt Au
 */
public class JobSchedulerEvent extends RemoteEvent {
    
    public final String message;
    
    /**
     * Constructor taking a single message as the argument
     * 
     * @param message String message to be sent with the event
     */
    public JobSchedulerEvent( String message ) {
        
        this.message = message;
    }
}
